import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import TheList from "@/components/TheList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tim&apos;s 40 b4 40</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TheList />
      </main>
    </>
  );
}
